//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QuickStart.rc
//
#define ID_EXIT                         1
#define IDC_RESET                       3
#define IDC_SELECT_PROGRAM_OTHER        3
#define SCQ_TYPE_SHELL                  4
#define SCQ_TYPE_FOLDER                 8
#define IDM_ABOUTBOX                    0x0010
#define IDM_SYSTRAY_ABOUT               0x0010
#define IDS_ABOUTBOX                    100
#define IDD_ABOUTBOX                    100
#define IDC_ADDQSO                      101
#define IDS_MODIFYQSO                   101
#define IDC_CONFIG                      102
#define IDD_QUICKSTART_DIALOG           103
#define IDB_UP                          104
#define IDB_DOWN                        105
#define IDR_CTMENU                      107
#define IDS_ADDQSO                      108
#define IDR_MAINFRAME                   108
#define IDS_ADDQSO_TYPE                 109
#define IDD_ADDQSO_TYPE                 109
#define IDC_ADDQSO_TYPE_PROGRAM         110
#define IDC_ADDQSO_TYPE_TASK            111
#define IDC_ADDQSO_TYPE_FOLDER          112
#define IDC_ADDQSO_TYPE_DOCUMENT        113
#define IDC_ADDQSO_TYPE_DOC             114
#define IDS_ADDQSO_PROGRAM              115
#define IDD_ADDQSO_PROGRAM              115
#define IDC_ADDQSO_PROGRAM_PATH         116
#define IDC_ADDQSO_PROGRAM_ARGUMENTS    117
#define IDS_ADDQSO_TASK                 118
#define IDD_ADDQSO_TASK                 118
#define IDC_ADDQSO_TASK_NAME            119
#define IDS_ADDQSO_FOLDER               120
#define IDD_ADDQSO_FOLDER               120
#define IDC_ADDQSO_TASK_DRIVES          120
#define IDC_ADDQSO_FOLDER_EXPLORE       121
#define IDC_ADDQSO_FOLDER_OPEN          122
#define IDC_ADDQSO_FOLDER_NAME          123
#define IDC_ADDQSO_FOLDER_PATH          123
#define IDS_ADDQSO_DOC                  124
#define IDD_ADDQSO_DOC                  124
#define IDC_ADDQSO_DOC_PATH             125
#define IDS_ADDQSO_HOTKEY               125
#define IDC_ADDQSO_DOC_ARGUMENTS        126
#define IDS_ADDQSO_NAME                 127
#define IDD_ADDQSO_NAME                 127
#define IDC_ADDQSO_NAME_NAME            128
#define IDS_ADDQSO_SUM                  129
#define IDD_ADDQSO_SUM                  129
#define IDS_NONAME                      130
#define IDD_ADDQSO_HOTKEY               130
#define IDS_FILENOTFOUND                131
#define IDS_NOEXECFILENAME              132
#define IDS_UNKNOWN                     133
#define IDS_NOFOLDERNAME                134
#define IDS_NODOCNAME                   135
#define IDS_REGHOTKEYFAILED             136
#define IDS_ONEINSTANCE                 137
#define IDS_SURE                        138
#define IDC_ADDQSO_SUMMARY_SUM          139
#define IDC_ADDQSO_SUM_SUM              139
#define IDS_NOTASK                      139
#define IDC_ADDQSO_SUM_SUM2             140
#define IDS_REMOVEALL                   140
#define IDS_LOADDEFCONFIG               141
#define IDS_UNSAFEHOTKEY                142
#define IDR_MAINFRAMEII                 143
#define IDS_COMMONHOTKEY                143
#define IDS_PATHNOTFOUND                144
#define IDB_BROWSE                      145
#define IDS_HOTKEYINUSE                 145
#define IDD_ADDQSO_HOTKEY_RECORD        146
#define IDS_DEFCFGDLLNOTFOUND           146
#define IDB_CONFIG                      149
#define IDB_ADDQSO                      150
#define IDB_HELP                        151
#define IDB_INFO                        151
#define IDB_CLOSE                       152
#define IDR_SYSTRAY                     153
#define IDD_QUICKSTART_CONFIG           154
#define IDI_TASK                        155
#define IDR_ACCELERATOR                 156
#define IDD_SELECT_PROGRAM              157
#define IDB_UPDIS                       158
#define IDB_DOWNDIS                     160
#define IDD_REGISTER                    161
#define IDD_WELCOME_1                   162
#define IDD_WELCOME                     162
#define IDD_TIP_MODIFYQSO               163
#define IDD_TIP_DISPLAYRESOLUTION       164
#define IDD_TIP_DISPLAYRESOLUTION_TEST  165
#define IDB_SCLOGO                      168
#define IDI_DISPLAYSETTINGS             169
#define IDC_SHUTDOWN                    1010
#define IDC_UP                          1011
#define IDC_DOWN                        1012
#define IDC_CTP_OPEN                    1012
#define IDC_LOGOFF                      1013
#define IDC_REBOOT                      1014
#define IDC_HOTKEY                      1017
#define IDC_CTP_EXPLORE                 1017
#define IDC_BROWSE                      1018
#define IDC_ADDQSO_ICON                 1025
#define IDC_ADDQSO_HOTKEY_HOTKEY        1028
#define IDC_ADDQSO_HOTKEY_RECORD        1029
#define IDC_ADDQSO_DOC_OPEN             1031
#define IDC_ADDQSO_PRINT_EXPLORE        1032
#define IDC_ADDQSO_DOC_PRINT            1032
#define ID_HIDE                         1033
#define ID_SHOW                         1034
#define IDC_AUTOSTART                   1034
#define IDC_SHOWSTART                   1035
#define IDC_ADDQSO_TASK_DRIVE           1035
#define IDC_CHOOSE_PROGRAM_LIST         1036
#define IDC_LIST1                       1037
#define IDC_ADDQSO_TASK_TEST            1038
#define IDC_CONFIG_LOADDEFCFG           1039
#define IDC_CONFIG_REMOVEALLQS          1040
#define ID_PURCHASE                     1042
#define IDC_WELCOME_MSG                 1043
#define IDC_WELCOME_DAYSLEFT            1045
#define ID_REGISTER                     1046
#define IDC_WELCOME_TITLE               1051
#define IDC_TIP_SHOWAGAIN               1053
#define IDC_REGISTER_NAME               1054
#define IDC_NAME                        1054
#define IDC_REGNUMBER                   1055
#define IDC_REGISTER_NUMBER             1055
#define IDC_WEB_HOME                    1056
#define IDC_WEB_SUPPORT                 1057
#define IDC_REGISTER                    1059
#define IDC_WELCOME_TIMEOUT             1060
#define IDC_WELCOME_FUNC2               1061
#define IDC_WELCOME_FUNC1               1062
#define IDC_WELCOME_TIMEOUT1            1063
#define IDC_WELCOME_TIMEOUT2            1064
#define IDC_WELCOME_TIMEOUT3            1065
#define IDC_BUTTON1                     2000
#define IDC_BUTTON2                     2001
#define IDC_BUTTON3                     2002
#define IDC_BUTTON4                     2003
#define IDC_BUTTON5                     2004
#define IDC_BUTTON6                     2005
#define IDC_BUTTON7                     2006
#define IDC_BUTTON8                     2007
#define IDC_LASTBUTTON                  5999
#define IDM_SYSMENUITEM1                6000
#define IDM_SYSMENUITEMLAST             9999
#define IDM_CTMENU_MODIFY               32770
#define IDM_CTMENU_ENABLE               32771
#define IDM_CTMENU_MOVE_LEFT            32772
#define IDM_CTMENU_MOVE_RIGHT           32773
#define IDM_CTMENU_MOVE_UP              32774
#define IDM_CTMENU_MOVE_DOWN            32775
#define IDM_CTMENU_MOVE_BEGIN           32786
#define IDM_CTMENU_MOVE_END             32787
#define ID_ABOUT                        32789
#define IDM_CTMENU_REMOVE               32790
#define IDM_SYSTRAY_FIRST               32790
#define IDM_SYSTRAY_SHOW                32791
#define IDM_SYSTRAY_LAST                32791
#define IDC_HIDE                        32811

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1062
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
